#!/bin/bash
# ── Keylone setup — External PostgreSQL ───────────────────────────────────────
#
# Generates .env with random JWT secret and prompts for domain.
# Does NOT create a PostgreSQL container — you provide the connection string.
#
# Usage:
#   chmod +x setup.external.sh
#   ./setup.external.sh
#   # Then edit .env and set DATABASE_URL to your PostgreSQL instance
# ─────────────────────────────────────────────────────────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "╔══════════════════════════════════════════╗"
echo "║    Keylone — Setup (External Postgres)   ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Detect docker compose command (v2 plugin or v1 standalone) ────────────────
if docker compose version >/dev/null 2>&1; then
    DC="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then
    DC="docker-compose"
else
    echo "❌ Neither 'docker compose' nor 'docker-compose' found."
    echo "   Install Docker with the Compose plugin: https://docs.docker.com/engine/install/"
    exit 1
fi

# ── Prerequisites ─────────────────────────────────────────────────────────────
command -v docker  >/dev/null 2>&1 || { echo "❌ docker is required but not found"; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo "❌ openssl is required but not found"; exit 1; }

echo "✓ Using: $DC"
echo ""

# ── Generate .env ─────────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    echo "✓ .env already exists — skipping generation"
    echo "  Delete $ENV_FILE to regenerate from scratch."
    echo ""
else
    echo "No .env found — generating credentials …"
    echo ""

    read -rp "  Domain / hostname (e.g. vault.example.com) [localhost]: " DOMAIN
    DOMAIN="${DOMAIN:-localhost}"

    if [ "$DOMAIN" = "localhost" ]; then
        ORIGIN="http://localhost:3000"
    else
        ORIGIN="https://$DOMAIN"
    fi

    JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=\n')

    cat > "$ENV_FILE" << EOF
# Keylone — generated by setup.external.sh on $(date)
# ⚠️  Keep this file secret — it contains JWT credentials.
#
# ── ACTION REQUIRED ───────────────────────────────────────────────────────────
# Set DATABASE_URL to your PostgreSQL connection string, for example:
#   postgresql://user:password@host:5432/keylone
#
# If PostgreSQL is running on the host machine (not in Docker), use:
#   postgresql://user:password@host.docker.internal:5432/keylone
# ─────────────────────────────────────────────────────────────────────────────

DATABASE_URL=postgresql://keylone:CHANGE_ME@host.docker.internal:5432/keylone
JWT_SECRET=${JWT_SECRET}
WEBAUTHN_RP_ID=${DOMAIN}
WEBAUTHN_ORIGIN=${ORIGIN}
TELEGRAM_PROXY=
EOF

    echo "✓ .env generated"
    echo "  Domain  → ${DOMAIN}"
    echo "  Origin  → ${ORIGIN}"
    echo ""
fi

# ── Remind to configure DATABASE_URL ─────────────────────────────────────────
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ⚠️  Edit .env before continuing!"
echo ""
echo "  Set DATABASE_URL to your PostgreSQL instance:"
echo "  postgresql://user:password@host:5432/keylone"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -rp "  Press Enter when .env is ready …"
echo ""

# ── Pull image and start ──────────────────────────────────────────────────────
echo "Pulling Keylone image …"
cd "$SCRIPT_DIR"
$DC -f docker-compose.external.yml pull

echo ""
echo "Starting Keylone …"
$DC -f docker-compose.external.yml up -d

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║  ✓ Keylone is running!                   ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "  URL:  http://localhost:3000"
echo ""
echo "  Logs: $DC -f docker-compose.external.yml logs -f"
echo "  Stop: $DC -f docker-compose.external.yml down"
echo ""
echo "  ⚠️  Back up your .env file — it contains your JWT secret."
