#!/bin/bash
# ── Keylone setup ─────────────────────────────────────────────────────────────
#
# Generates .env with random credentials and starts Keylone + PostgreSQL.
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "╔══════════════════════════════════════════╗"
echo "║           Keylone — Setup                ║"
echo "╚══════════════════════════════════════════╝"
echo ""

# ── Prerequisites ─────────────────────────────────────────────────────────────
command -v docker  >/dev/null 2>&1 || { echo "❌ docker is required but not found"; exit 1; }
docker compose version >/dev/null 2>&1 || { echo "❌ docker compose plugin is required"; exit 1; }
command -v openssl >/dev/null 2>&1 || { echo "❌ openssl is required but not found"; exit 1; }

# ── Generate .env ─────────────────────────────────────────────────────────────
if [ -f "$ENV_FILE" ]; then
    echo "✓ .env already exists — skipping generation"
    echo "  Delete $ENV_FILE to regenerate from scratch."
    echo ""
else
    echo "No .env found — generating credentials …"
    echo ""

    read -rp "  Domain / hostname (e.g. vault.example.com) [localhost]: " DOMAIN
    DOMAIN="${DOMAIN:-localhost}"

    if [ "$DOMAIN" = "localhost" ]; then
        ORIGIN="http://localhost:3000"
    else
        ORIGIN="https://$DOMAIN"
    fi

    POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=\n')
    JWT_SECRET=$(openssl rand -base64 48 | tr -d '/+=\n')

    cat > "$ENV_FILE" << EOF
# Keylone — generated by setup.sh on $(date)
# ⚠️  Keep this file secret — it contains database and JWT credentials.

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
WEBAUTHN_RP_ID=${DOMAIN}
WEBAUTHN_ORIGIN=${ORIGIN}
TELEGRAM_PROXY=
EOF

    echo "✓ .env generated"
    echo "  Domain  → ${DOMAIN}"
    echo "  Origin  → ${ORIGIN}"
    echo ""
fi

# ── Pull image and start ──────────────────────────────────────────────────────
echo "Pulling Keylone image …"
cd "$SCRIPT_DIR"
docker compose pull keylone

echo ""
echo "Starting Keylone + PostgreSQL …"
docker compose up -d

echo ""
echo "╔══════════════════════════════════════════╗"
echo "║  ✓ Keylone is running!                   ║"
echo "╚══════════════════════════════════════════╝"
echo ""
echo "  URL:  http://localhost:3000"
echo ""
echo "  Logs: docker compose logs -f"
echo "  Stop: docker compose down"
echo ""
echo "  ⚠️  Back up your .env file — it contains your database credentials."
